{% set name = "autoclick" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoclick-{{ version }}.tar.gz
  sha256: 583b1c7e57eedd4a9a61b35ff5fbf491d3eb1fedda5895ffaffad7baaf6786d8

build:
  noarch: python
  script:
    - {{ PYTHON }} -c '__import__("os").unlink("pyproject.toml")'
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.6,<4.0
    - click ==7.0
    - docparse

test:
  imports:
    - autoclick
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jdidion/autoclick
  summary: Auto-generate Click-based CLIs from python3 type annotations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthdsm
